name: mezgebe_sbhat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  dio: ^5.5.0+1
  flutter_ffmpeg: ^0.4.2
  flutter:
    sdk: flutter
  provider: ^6.1.2
  syncfusion_flutter_pdfviewer: ^26.2.4
  path_provider: ^2.1.3
  getwidget: ^4.0.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  path: ^1.9.0
  retry: ^3.1.2
  flutter_slidable: ^3.1.1
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#000000"
  image: "assets/images/splash.png"
  branding: "assets/images/branding.png"

  android_12:
    color: "#000000"
    image: "assets/images/splash_adaptive.png"
    branding: "assets/images/branding.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
